# Generated by Django 4.0.4 on 2024-06-23 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must consist of letters, numbers, or @/./+/-/_ characters.', regex='^[\\w@./+-]+$')]),
        ),
    ]
