# Generated by Django 4.0.4 on 2024-06-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnotification',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='repost_blog',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='postnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PostNotification',
        ),
    ]
